database:
  development:
    url: postgres://<username>:<password>@<host>/<database>

application:
  secret_key: HMAC_SECRET
  algorithm: HS256
  app_expires_in: 3600
  refresh_token_expires_in: 604800